package com.ftofs.lib_net.model

import java.io.Serializable


data class PropertyVo(
        val additionalFeaturesType: String,
        val age: Int,
        val area: String,
        val brokeragePercent: Int,
        val brokerageType: Int,
        val building: String,
        val buildingArea: Int,
        val city: String,
        val contactHits: Int,
        val cooperation: Int,
        val cover: String,
        val coverkey: Int,
        val decoration: Int,
        val decorationDescription: String,
        val detail: String,
        val developers: String,
        val direction: Int,
        val editDate: String,
        val email: String,
        val expireDate: String,
        val floor: String,
        val furniture: String,
        val goodPick: Int,
        val handPick: Int,
        val hits: Int,
        val intervalHall: Int,
        val intervalRoom: Int,
        val intervalStoreRooms: Int,
        val intervalTerrace: Int,
        val intervalToilet: Int,
        val isLift: Int,
        val isNew: Int,
        val isParkingSpaces: Int,
        val isStatus: Int,
        val isTop: Int,
        val isType: Int,
        val landscape: String,
        val landscapeDescription: String,
        val lease: Int,
        val linkMan: String,
        val loftDescribe: Int,
        val mHandPick: Int,
        val map_X: String,
        val map_Y: String,
        val mobile: String,
        val other: Int,
        val parkingSpaces: String,
        val picAmount: Int,
        val pid: Int,
        val propertyCorp: String,
        val propertyName: String,
        val pubDate: String,
        val remark: String,
        val rentReservePrice: Int,
        val rentalPrice: Int,
        val roomType: Int,
        val salableArea: Int,
        val saleDate: Any,
        val saleType: Int,
        val selected: Int,
        val sellReservePrice: Int,
        val sellingPrice: Int,
        val sequence: Int,
        val source: Int,
        val street: String,
        val tel: String,
        val tid: Int,
        val ui_Other: Int,
        val ui_isStatus: Int,
        val uid: Int,
        val unit: String,
        val unitPrice: Int,
        val photoList:List<GoPhoto>
):Serializable{
    fun getTypeName():String=when(isType){
        else ->"住宅"
    }
}
data class GoPhoto(
        val isDefault: Int,
        val monthPic: Int,
        val photoId: Int,
        val remark: String,
        val rollShow: Int,
        val sortimg: Int,
        val title: String
):Serializable

